spring:
  application:
    name: store
  config.import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15m
    refreshTokenExpiration: 604800 # 7d
app:
  user-path: /api/users