spring:
  application:
    name: store
  config.import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
#  level:
#    root: debug

app:
  user-path: /api/users
  admin-path: /api/admin
  auth-path: /api/auth