spring:
  application:
    name: store
  config.import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5m
    refreshTokenExpiration: 604800 # 7d
    verificationExpiration: 900 # 15m
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS} #<login user to smtp server>
    password: ${MAIL_PASSWORD} #<login password to smtp server>
    properties.mail:
      mime:
        charset: UTF
      smtp:
        auth: true
        starttls:
          enable: true
    default-encoding: UTF-8

app:
  base-uri: http://localhost:8080
  api: /api
  user-path: ${app.api}/users
  admin-path: ${app.api}/admin
  auth-path: ${app.api}/auth
  product-path: ${app.api}/products
  cart-path: ${app.api}/carts
