spring:
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    accessTokenExpiration: 90000 # 1500m
    refreshTokenExpiration: 604800 # 7d

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
#  level:
#    root: debug
